### ISSUE TITLE
glusterd.info gets messed up -- UUID=00000000-0000-0000-0000-000000000000 operating-version=1

### ISSUE THREAD

**Issue by jackdpeterson** [purpleidea/puppet-gluster#36]
OS: CentOS 6.x
Gluster: 3.6.2

After upgrading from a previous version of puppet-gluster (as well as attempting a downgrade from current ~ae24ecc28844404ff3b29ff80230a1564485b2b8
) I'm noticing that the glusterd.info gets the incorrect data put in. If I manually edit the file with the correct information gluster is fine; however, something (not sure exactly where) is causing the UUID to be set to all zeroes. 

$ sudo gluster pool list
pool list: failed

$ sudo gluster peer status
peer status: failed

Some starting log data...
[2015-03-10 04:41:25.003181] I [MSGID: 106004] [glusterd-handler.c:4365:__glusterd_peer_rpc_notify] 0-management: Peer 00000000-0000-0000-0000-000000000000, in Peer is connected and Accepted state, has disconnected from glusterd.
[2015-03-10 04:41:25.141972] I [glusterd-handshake.c:1119:__glusterd_mgmt_hndsk_versions_ack] 0-management: using the op-version 1
[2015-03-10 04:41:25.142057] I [glusterd.c:146:glusterd_uuid_init] 0-management: retrieved UUID: 00000000-0000-0000-0000-000000000000
[2015-03-10 04:41:25.148064] I [glusterd-handler.c:2216:__glusterd_handle_incoming_friend_req] 0-glusterd: Received probe from uuid: 00000000-0000-0000-0000-000000000000

Manifest definition...

 ## DEFINE $1 (which was supposed to be dynamic, but instead has issues due to UUID generation...)
     

        $pod_number = "1"

        $gl_ip_1 = "gluster1.pod${pod_number}.example.com" #US-EAST1-B
        $gl_ip_2 = "gluster2.pod${pod_number}.example.com"        #US-EAST1-B
        $gl_ip_3 = "gluster3.pod${pod_number}.example.com"        #US-EAST1-D

        file {"/tmp/gluster_servers.txt":
                ensure => present,
                content => "1 - ${gl_ip_1}, 2 - ${gl_ip_2}, 3 - ${gl_ip_3}.. \$1 == ${pod_number}"
        }

        class { 'gluster::server':
                ips => ["${gl_ip_1}", "${gl_ip_2}", "${gl_ip_3}"],
                shorewall => false,
                repo => true,
        }

        ## Allow puppet master to control UUIDs. This may need to be modified later to fully spec out gluster

        gluster::host { "gluster1.pod${pod_number}.example.com":
                ip => "10.0.5.5",
                uuid => "e7534140-1cdd-4bef-a57b-c5ed308393ea"
        }

        gluster::host { "gluster2.pod${pod_number}.example.com":
                ip => "10.0.5.6",
                uuid => "76f1fcbd-d786-4c0b-b69f-8ddfdbf9c1bf",
        }

        gluster::host { "gluster3.pod${pod_number}.example.com":
                ip => "10.0.6.5",
                uuid => "932bc8b1-6129-4f6f-9f1b-d0f7e9c48a79"

        }

        ## main volume
                gluster::brick { "gluster1.pod${pod_number}.example.com:/mnt/storage1j":
                        dev => '/dev/xvdf', ## AWS - /dev/sdf
                        labeltype => 'gpt',
                        fstype => 'xfs',
                        xfs_inode64 => true,
                        xfs_nobarrier => true,
                        areyousure => true,
                }

                gluster::brick { "gluster2.pod${pod_number}.example.com:/mnt/storage2j":
                        dev => '/dev/xvdf', ## AWS - /dev/sdf
                        labeltype => 'gpt',
                        fstype => 'xfs',
                        xfs_inode64 => true,
                        xfs_nobarrier => true,
                        areyousure => true,
                }

                gluster::brick { "gluster3.pod${pod_number}.example.com:/mnt/storage3j":
                        dev => '/dev/xvdf', ## AWS - /dev/sdf
                        labeltype => 'gpt',
                        fstype => 'xfs',
                        xfs_inode64 => true,
                        xfs_nobarrier => true,
                        areyousure => true,
                }

                $brick_list = [
                        "gluster1.pod${pod_number}.example.com:/mnt/storage1j",
                        "gluster2.pod${pod_number}.example.com:/mnt/storage2j",
                        "gluster3.pod${pod_number}.example.com:/mnt/storage3j"
                ]

                gluster::volume { "pod${pod_number}":
                        replica => "3",
                        bricks => $brick_list,
                        start => undef,
                        transport => "tcp"
                }

                ## QUORUM depends on at least 2 nodes being available
                gluster::volume::property { "pod${pod_number}#cluster.quorum-count":
                        value => "2"
                }

                ## set client-side quorum to fixed
                gluster::volume::property { "pod${pod_number}#cluster.quorum-type":
                        value => "fixed"
                }

$ sudo puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
No volumes present in cluster
Info: Caching catalog for gluster1.pod1.example.com
Info: Applying configuration version '1425962437'
Notice: /Stage[main]/Gluster::Vardir/File[/var/lib/puppet/tmp/gluster/vrrp]/ensure: removed
Notice: /Stage[main]/Main/Node[gluster1-3.pod1.example.com]/Gluster::Host[gluster1.pod1.example.com]/File[/var/lib/glusterd/glusterd.info]/content:
--- /var/lib/glusterd/glusterd.info     2015-03-10 04:41:25.154754385 +0000
+++ /tmp/puppet-file20150310-21000-23dxof-0     2015-03-10 04:42:37.174942021 +0000
@@ -1,2 +1,4 @@
-UUID=00000000-0000-0000-0000-000000000000
-operating-version=1
+UUID=e7534140-1cdd-4bef-a57b-c5ed308393ea
+
+operating-version=30600
+

Info: Computing checksum on file /var/lib/glusterd/glusterd.info
Info: FileBucket got a duplicate file {md5}ba880421fd1f536c75e311664db7e7d8
Info: /Stage[main]/Main/Node[gluster1-3.pod1.example.com]/Gluster::Host[gluster1.pod1.example.com]/File[/var/lib/glusterd/glusterd.info]: Filebucketed /var/lib/glusterd/glusterd.info to puppet with sum ba880421fd1f536c75e311664db7e7d8
Notice: /Stage[main]/Main/Node[gluster1-3.pod1.example.com]/Gluster::Host[gluster1.pod1.example.com]/File[/var/lib/glusterd/glusterd.info]/content: content changed '{md5}ba880421fd1f536c75e311664db7e7d8' to '{md5}c33e1eaaed3ba5985048a74065e710e5'
Info: /Stage[main]/Main/Node[gluster1-3.pod1.example.com]/Gluster::Host[gluster1.pod1.example.com]/File[/var/lib/glusterd/glusterd.info]: Scheduling refresh of Service[glusterd]
Notice: /Stage[main]/Gluster::Server/Service[glusterd]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 5.48 seconds

Subsequent re-executions result in the same information -- glusterd.info is modified ... then re-modified at the last second. glusterd is restarted (notified) and then the whole set of gluster instances gets hosed.

Any thoughts on what files to look at/delete as part of a clean-up on the puppet-master as well as client systems?

Some things that didn't help:
1. rebooting instances
2. rm -rf on /varlib/glusterd/* 
3. deleting the bricks in their entirety (dd if=/dev/zero of=/dev/evice bs=1M) and attempting a reconstruction from the beginnning...

**Comment by purpleidea** [comment]
@jackdpeterson From your logs:

```
 Notice: /Stage[main]/Main/Node[gluster1-3.pod1.example.com]/Gluster::Host[gluster1.pod1.example.com]/File[/var/lib/glusterd/glusterd.info]/content:
--- /var/lib/glusterd/glusterd.info 2015-03-10 04:41:25.154754385 +0000
+++ /tmp/puppet-file20150310-21000-23dxof-0 2015-03-10 04:42:37.174942021 +0000
@@ -1,2 +1,4 @@
-UUID=00000000-0000-0000-0000-000000000000
-operating-version=1
+UUID=e7534140-1cdd-4bef-a57b-c5ed308393ea
+
+operating-version=30600
+
```

This looks as if puppet is REMOVING the 0000.... and putting in the correct value. I'm not sure what's causing it to change outside of the puppet run. Glusterd perhaps? I'd recommend stopping puppet entirely, checking that the UUID's are correct, and then seeing if they change.

Search down that path and see what comes up. For the moment, it doesn't look like puppet-gluster is to blame here, so I will close this report for now, but if you have evidence of otherwise, or I've misunderstood, I'll happily re-open.

HTH,
James

**Comment by purpleidea** [comment]
PS: after you narrow down that it's not puppet, ask in #gluster if you can't figure out what's going on. They're good at knowing about such weird things the daemon might do.

**Comment by jackdpeterson** [comment]
Thanks. I also pasted in the existing puppet-gluster configuration to help better document the issue at the moment.

**Comment by purpleidea** [comment]
@jackdpeterson AFAICT, the config looks correct, although it is worth pointing out that it is the "manual" config, and using "gluster::simple" might be useful for a new cluster.
https://github.com/purpleidea/puppet-gluster/blob/master/DOCUMENTATION.md#simple-setup

**Comment by jackdpeterson** [comment]
Ruled out puppet-gluster as the root-cause for the moment. Manually re-set the glusterd.info file to what vlaues should be. chkconfig'd puppet off. bounced systems. UUIDs hosed.

**Comment by jackdpeterson** [comment]
Just doing a bit of digging to see where this could have come from...

Searching 1600 files for "00000000-0000-0000-0000-000000000000"

C:\github\glusterfs\libglusterfs\src\inode.c:
 1281  
 1282          if (!__is_root_gfid (itrav->gfid)) {
 1283:                 /* "<gfid:00000000-0000-0000-0000-000000000000>"/path */
 1284                  i += GFID_STR_PFX_LEN;
 1285          }

C:\github\glusterfs\libglusterfs\src\inode.h:
  103  
  104  
  105: #define UUID0_STR "00000000-0000-0000-0000-000000000000"
  106  #define GFID_STR_PFX "<gfid:" UUID0_STR ">"
  107  #define GFID_STR_PFX_LEN (sizeof (GFID_STR_PFX) - 1)

C:\github\glusterfs\xlators\storage\posix\src\posix-handle.h:
   28  #define TRASH_DIR "landfill"
   29  
   30: #define UUID0_STR "00000000-0000-0000-0000-000000000000"
   31  #define SLEN(str) (sizeof(str) - 1)
   32  

3 matches across 3 files


Searching 1600 files for "UUID0_STR"

C:\github\glusterfs\libglusterfs\src\inode.h:
  103  
  104  
  105: #define UUID0_STR "00000000-0000-0000-0000-000000000000"
  106: #define GFID_STR_PFX "<gfid:" UUID0_STR ">"
  107  #define GFID_STR_PFX_LEN (sizeof (GFID_STR_PFX) - 1)
  108  

C:\github\glusterfs\xlators\storage\posix\src\posix-handle.c:
  202                  + SLEN("00/")
  203                  + SLEN("00/")
  204:                 + SLEN(UUID0_STR)
  205                  + 1 /* '\0' */
  206                  ;
  ...
  405                  + SLEN("00/")
  406                  + SLEN("00/")
  407:                 + SLEN(UUID0_STR)
  408                  + 1 /* '\0' */
  409                  ;

C:\github\glusterfs\xlators\storage\posix\src\posix-handle.h:
   28  #define TRASH_DIR "landfill"
   29  
   30: #define UUID0_STR "00000000-0000-0000-0000-000000000000"
   31  #define SLEN(str) (sizeof(str) - 1)
   32  
   33  #define HANDLE_ABSPATH_LEN(this) (POSIX_BASE_PATH_LEN(this) + \
   34                                    SLEN("/" GF_HIDDEN_PATH "/00/00/" \
   35:                                   UUID0_STR) + 1)
   36  
   37  #define LOC_HAS_ABSPATH(loc) (loc && (loc->path) && (loc->path[0] == '/'))

C:\github\glusterfs\xlators\storage\posix\src\posix.h:
   59                                                 + SLEN(GF_HIDDEN_PATH) + SLEN("/") \
   60                                                 + SLEN("00/")            \
   61:                                                + SLEN("00/") + SLEN(UUID0_STR) + 1) /* '\0' */;
   62  
   63  /**

7 matches across 4 files

**Comment by purpleidea** [comment]
@jackdpeterson This is the issue tracker for puppet-gluster, not upstream GlusterFS. Paste that stuff there. This issue is closed :)

**Comment by jackdpeterson** [comment]
Requesting that we re-open this issue. I just attempted to create a clean gluster server configuration across all new instances using Ubuntu 14.04 this time. Same result -- UUIDs get hosed into 0000. This has to have something to do with either my configuration.

Additonal step to perform (sudo apt-get install lvm2).

each disk at /dev/xvdf was zeroed out.

New puppet-cluster configuration:

node ex_gluster_ubuntu inherits example_no_upgrades{
	include apt
	apt::ppa {'ppa:gluster/glusterfs-3.6':
 	}

	include swap_file

	$utils_list = ["nload", 
			 "parted",
			]

	package{ $utils_list:
		ensure => ['installed','latest']
	}
    }
}

## A Quorum enabled -- Replica 3 configuration for gluster. While having lower write performance, this will enfore higher consistency as bricks will become read-only if < (2/3) bricks are available

node /^gluster[1-3]+\.pod1\.example\.com$/ inherits ex_gluster_ubuntu {
	## DEFINE $1 (which was supposed to be dynamic, but instead has issues...)
	$pod_number = "1"

	$gl_ip_1 = "gluster1.pod${pod_number}.example.com" 	#US-EAST1-B
	$gl_ip_2 = "gluster2.pod${pod_number}.example.com"	#US-EAST1-B
	$gl_ip_3 = "gluster3.pod${pod_number}.example.com"	#US-EAST1-D

	file {"/tmp/gluster_servers.txt":
		ensure => present,
		content => "1 - ${gl_ip_1}, 2 - ${gl_ip_2}, 3 - ${gl_ip_3}.. \$1 == ${pod_number}"
	}

	class { 'gluster::server':
		ips => ["${gl_ip_1}", "${gl_ip_2}", "${gl_ip_3}"],
		shorewall => false,
		repo => false,
	}

	## Allow puppet master to control UUIDs. This may need to be modified later to fully spec out gluster

	gluster::host { "gluster1.pod${pod_number}.example.com":
		ip => "10.0.5.5",
		uuid => "e7534140-1cdd-4bef-a57b-c5ed308393ea"
	}

	gluster::host { "gluster2.pod${pod_number}.example.com":
		ip => "10.0.5.6",
		uuid => "76f1fcbd-d786-4c0b-b69f-8ddfdbf9c1bf",
	}

	gluster::host { "gluster3.pod${pod_number}.example.com":
		ip => "10.0.6.5",
		uuid => "932bc8b1-6129-4f6f-9f1b-d0f7e9c48a79"

	}

	## main volume
		gluster::brick { "gluster1.pod${pod_number}.example.com:/mnt/storage1j":
			dev => '/dev/xvdf', ## AWS - /dev/sdf
			labeltype => 'gpt',
			fstype => 'xfs',
			xfs_inode64 => true,
			xfs_nobarrier => true,
			areyousure => true,
		}

		gluster::brick { "gluster2.pod${pod_number}.example.com:/mnt/storage2j":
			dev => '/dev/xvdf', ## AWS - /dev/sdf
			labeltype => 'gpt',
			fstype => 'xfs',
			xfs_inode64 => true,
			xfs_nobarrier => true,
			areyousure => true,
		}

		gluster::brick { "gluster3.pod${pod_number}.example.com:/mnt/storage3j":
			dev => '/dev/xvdf', ## AWS - /dev/sdf
			labeltype => 'gpt',
			fstype => 'xfs',
			xfs_inode64 => true,
			xfs_nobarrier => true,
			areyousure => true,
		}

		$brick_list = [
			"gluster1.pod${pod_number}.example.com:/mnt/storage1j",
			"gluster2.pod${pod_number}.example.com:/mnt/storage2j",
			"gluster3.pod${pod_number}.example.com:/mnt/storage3j"
		]

		gluster::volume { "pod${pod_number}":
			replica => "3",
			bricks => $brick_list,
			start => undef,
			transport => "tcp"
		}

		## QUORUM depends on at least 2 nodes being available
		gluster::volume::property { "pod${pod_number}#cluster.quorum-count":
			value => "2"
		}

		## set client-side quorum to fixed
		gluster::volume::property { "pod${pod_number}#cluster.quorum-type":
			value => "fixed"
		}
}

**Comment by jackdpeterson** [comment]
RESOLVED!!! 

This entirely has to do with how sourcetree clones in the repositories. It appears that I either had a conflict in the submodules that sourcetree clones in or that there is some odd transposition of line endings or something funky with how it handles the git repository inside of the mercurial repository that I have configured. The solution to this is to git clone URL /etc/puppet/modules/gluster directly in linux directly and calling it good.

**Comment by purpleidea** [comment]
@jackdpeterson Yikes! I guess this is a good reminder that whenever M$ or Windows is involved, someone is going to have a bad day!

Do you mind adding a patch to the FAQ describing the issue you saw, and the solution?
(I'll re-open an assign to you!)

Thanks!

**Comment by purpleidea** [comment]
Assigned to @jackdpeterson
