### ISSUE TITLE
Invalid relationship on gluster servers

### ISSUE THREAD

**Issue by aamerik** [purpleidea/puppet-gluster#43]
Hi James,

I pulled in the latest master and now my gluster servers are erroring on:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/appdata/bricks/brick001/] { require => Exec[gluster-brick-mkfs-gls001.lab1.ca1.foo.co:/appdata/bricks/brick001] }, because Exec[gluster-brick-mkfs-gls001.lab1.ca1.foo.co:/appdata/bricks/brick001] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Have you seen this before?

Alexey

**Comment by purpleidea** [comment]
It's possible you had a different cluster before and have some stale exported resources stored...

Clear those and try again, or more specifically, run puppet to clear those on the node that created the old ones.

**Comment by aamerik** [comment]
@purpleidea the issue is on line https://github.com/purpleidea/puppet-gluster/blob/master/manifests/brick.pp#L542

It should be require => Exec["gluster-brick-mkdir-${name}"],

Instead it reads require => Exec["gluster-brick-mkfs-${name}"],

I verified this as a fix, will put in a PR.
Alexey

**Comment by purpleidea** [comment]
Good find, merged thanks to your patch.

Thanks!
