### ISSUE TITLE
stdlib 4.6.0 introduces a significant change (and broken w/ future-parser)

### ISSUE THREAD

**Issue by sysadmin1139** [purpleidea/puppet-gluster#46]
[Specifically](https://forge.puppetlabs.com/puppetlabs/stdlib/changelog), `type` is deprecated in favor of `type3x`. Which looks to be done for future-parser compatibility. Now that puppet 4.0 is out, this is somewhat more important. It's probably time to update the module dependencies.

**Comment by sysadmin1139** [comment]
The markup to reflect the incompatibility looks pretty simple:

metadata.json:

    "dependencies": [
		{ "name": "puppetlabs/stdlib", "version_requirement": ">= 4.0.0 < 4.6.0" }
	]

**Comment by purpleidea** [comment]
@sysadmin1139 I haven't had a chance to test this much on 4.x -- Please do, and if the only change is the metadata.json file, then I'll happily accept patches.

**Comment by sysadmin1139** [comment]
Well then. #47 submitted to address this in the near term. I'm unclear on how to solve this and support both 3x and 4x parsers.

**Comment by purpleidea** [comment]
@sysadmin1139 Merged, thanks.

If you plan to write additional patches for this issue, please do. Otherwise let's close until someone else is bothered by this 4.x issue.

Thanks again :)

**Comment by sysadmin1139** [comment]
From how I'm reading it, the recommended pattern here is to transition to the new `type_of` function and also use the new parser. Which doesn't help people still on the 3x series and the old parser. I suspect the 'fix' here will be to move everything to type3x, update the dependencies to say `stdlib >= 4.6.0`, and increment the version number here to reflect the updated requirements. Looking at the diffs, the `type3x` function is the same as `type`, just lacking the deprecation warning.

As stdlib 4.6.0 is a week old, it may be too early for that!

**Comment by sysadmin1139** [comment]
Version 0.1.0 stomps this issue flat.
