### ISSUE TITLE
Error while evaluating a Resource Statement, Permission denied

### ISSUE THREAD

**Issue by cova-fe** [purpleidea/puppet-gluster#62]
While trying to run this module to install glusterfs on a node, I get this error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Permission denied - /etc/puppetlabs/code/environments/production/modules/gluster/manifests/host/data.pp at /etc/puppetlabs/code/environments/production/modules/gluster/manifests/host.pp:54:3 on node xxxx

It seems caused by the invocation of class data in file host.pp, but I can't see anything wrong in configuration. Any Idea?

Thanks.

**Comment by purpleidea** [comment]
No idea, but double check if the file permissions are correct and that the selinux contexts are too...

Doesn't sound like a puppet-gluster issue though. Let me know if you get better info.

**Comment by purpleidea** [comment]
In addition, maybe the folks in #puppet have seen this error before.

**Comment by cova-fe** [comment]
it turned out that the data.pp under host was 660 and not 664, thus preventing puppet to read it.
Thanks for the hint; now I have to understand why it was 660.

**Comment by purpleidea** [comment]
@cova-fe awesome!
